name: test

on:
  schedule:
      - cron: '*/2 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Running
      run: |
        echo "Running!"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install os
        pip install pygsheets
        pip install numpy
    - name: Run test.py
      run: |
        python ./test.py
